### ISSUE TITLE
Antag Panel is broken?

### ISSUE THREAD

**Issue by nevimer** [Artea-Station/Artea-Station-Server#143]
## Testmerges:
#139 
## Reproduction:
![dreamseeker_8TOva9elqL](https://user-images.githubusercontent.com/77420409/230260291-b27e13ab-92b0-4b28-a5af-3970672af487.png)

**Comment by RimiNosha** [comment]
That should be resolved via removing the antag entries in TGUI. I can't fucking belive that's hardcoded.

**Comment by QuacksQ** [comment]
![image](https://user-images.githubusercontent.com/79924768/230747011-3dbad390-0cd9-48d5-bef0-ddccd90974d0.png)
