### ISSUE TITLE
Strange lighting behavior on walls

### ISSUE THREAD

**Issue by QuacksQ** [Artea-Station/Artea-Station-Server#226]
## Reproduction:

Simply load up your master branch, go to Kilostation and go to the locations shown in the images and videos. Lighting behavior is really weird around the walls shown and I have a feeling that this might have been caused by #205. Just pointing this out and making the issue so we can keep track of it and are aware :P

### The weird lighting in question:

![image](https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/275def8f-bd87-4979-a683-cf7cfc8f86d0)

![image](https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/c6a1274b-7cf3-4b36-9e7e-5434c042057f)

### 2x2 walls appear as blocked vision.

https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/d09e168f-96c1-4411-8516-816e4d82a101

**Comment by RimiNosha** [comment]
I have a feeling this is a side effect of not having proper line of sight overlay support for the walls

**Comment by Kapu1178** [comment]
the dmi was not properly editted so the fallback sprite is failing, it probably doesn't exist.

**Comment by RimiNosha** [comment]
Turns out I was looking at an out of date file

**Comment by RimiNosha** [comment]
Anyways, part of this is intended behavior, and just looks weird because I haven't figured out a good way to handle partial visibility overlays on walls without kneecapping performance yet.
