### ISSUE TITLE
Menu mouse detection is offset.

### ISSUE THREAD

**Issue by DrAlexzander17** [Artea-Station/Artea-Station-Server#430]
![image](https://github.com/Artea-Station/Artea-Station-Server/assets/152810230/ef00c18f-f760-44a0-a85d-99b6bc325e4b)

**Comment by RimiNosha** [comment]
Is it the same when you join the game/observe?

**Comment by RimiNosha** [comment]
515 related.

**Comment by nevimer** [comment]
fixed in 1621
