### ISSUE TITLE
Holomaps are still broken and cannot be closed.

### ISSUE THREAD

**Issue by QuacksQ** [Artea-Station/Artea-Station-Server#527]
## Testmerges:

No test merges this his happening on Master.

## Reproduction:

Go to a Holomap open it, and try closing it goodluck. No runtimes this time either :(
Pressing keys or clicking anywhere in the display doesn't work either and you will not be able to close out of the Holomap. 

https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/b573dd02-8b40-4b69-b1c6-fedd00457430

**Comment by RimiNosha** [comment]
Update: Happens for me on the latest stable 515 release. Looking into it.
