### ISSUE TITLE
Air alarm offset is wonky

### ISSUE THREAD

**Issue by QuacksQ** [Artea-Station/Artea-Station-Server#536]
## Round ID:

Round ID: 145

## Testmerges:

#510 
#511 
#531 

## Reproduction:

Just look around the map on the server.

![image](https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/5cff61aa-297f-4546-9008-8fa4c0e87dd0)

![image](https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/f5c87250-af4d-4d5a-ae17-e34a193bc72e)

![image](https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/fb419ef7-ec8f-439b-b534-391a9e9acb25)

**Comment by RimiNosha** [comment]
Fixed by latest commit in #531
