### ISSUE TITLE
Crowbars straight up dont work on firelocks

### ISSUE THREAD

**Issue by QuacksQ** [Artea-Station/Artea-Station-Server#538]
## Testmerges:

#511 
#510 
#531 

## Reproduction:

Grab a crowbar and try using it on a firelock the game wont do anything and returns a small message to you in chat as it runtimes. 

### The runtime in question
![image](https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/a07964e7-5733-48ad-a127-f698e88ffbf0)

### Video demo 

https://github.com/Artea-Station/Artea-Station-Server/assets/79924768/1cb6051b-ef12-4ee8-904a-c6b0a937c705

**Comment by RimiNosha** [comment]
Fixed by the latest commit in #531
